repos:
  - repo: https://github.com/hhatto/autopep8.git
    rev: v2.3.1 # Use the appropriate version
    hooks:
      - id: autopep8
        args: [--in-place, --global-config, .pep8]
        additional_dependencies: []

  - repo: https://github.com/pylint-dev/pylint.git
    rev: v3.2.6 # Use the appropriate version
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        additional_dependencies: []
